### ISSUE TITLE
[DrawInspector] bug

### ISSUE THREAD

**Issue by emmanuel-dev000** [uurha/BetterAttributes#69]
There's a bug in the editor when using [DrawInspector]:

Before Collapsing:
![image](https://user-images.githubusercontent.com/110382530/235426846-8f307d14-bebd-49c5-a5ee-d9edba1c3106.png)

After Collapsing:
![image](https://user-images.githubusercontent.com/110382530/235426893-b3abfd6a-465c-4edf-866b-03f20d426b61.png)

Code:
![image](https://user-images.githubusercontent.com/110382530/235426936-2ff53bc7-0786-491a-8350-ca3e4f449b82.png)

Expected Collapse:
![image](https://user-images.githubusercontent.com/110382530/235426991-a4b6b9b2-00f4-45cb-9411-95039cab5558.png)

I hope this can help you improve this plugin.

**Comment by emmanuel-dev000** [comment]
Although, it's fine with the given Test Scene example.
![image](https://user-images.githubusercontent.com/110382530/235427378-061ee1d1-1b65-4bfb-a080-e2182a24dcb1.png)

**Comment by emmanuel-dev000** [comment]
Here's the code for PlayerControllerData btw.
![image](https://user-images.githubusercontent.com/110382530/235427586-44340cae-d7c6-4a3a-9e47-24b7155f91ee.png)

**Comment by uurha** [comment]
Hi, @emmanuel-dev000, could you tell me please, which unity version do you use?

**Comment by emmanuel-dev000** [comment]
Sure. I have Unity 2021.3.16f1.
Other plugins/packages in project: [VContainer](https://vcontainer.hadashikick.jp/)

Didn't use the VContainer to the code though. If that might help.

**Comment by emmanuel-dev000** [comment]
Here's the repository/script btw. Also included a .unitypackage.
https://github.com/emmanuel-dev000/Game-System-Design/blob/main/Brick%20Break%20Game/Scripts/PlayerController.cs

**Comment by uurha** [comment]
Soon will be new version with fix

**Comment by emmanuel-dev000** [comment]
Hey, thanks for solving that selfish issue of mine! Awesome.

**Comment by uurha** [comment]
@emmanuel-dev000 just pushed new release, let me know if you have any bugs. You can create a new issue or reopen this one

**Comment by uurha** [comment]
@emmanuel-dev000 fyi `[SelectEnumAttribute]` and `[SelectImplementationAttribute]` were replaces with single `[SelectAttribute]`
